### ISSUE TITLE
Parsing of Microsoft TL results in toString error

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#37]
@fotisl added microsoft parsing for us but its not working for me.

```
Ryans-MBP:bin rmh$ node tl-create.js --microsoft --format pem roots.pem
Parsing started: 2016:10:08:17:04:09
Trust Lists: Microsoft
TypeError: tl_create.Microsoft is not a constructor
Output format: PEM
/Users/rmh/tl-create/src/bin/tl-create.js:243
            writableStream.write(tl.toString());
                                   ^

TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (/Users/rmh/tl-create/src/bin/tl-create.js:243:36)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by fotisl** [comment]
There is another error before the toString() error, 'TypeError: tl_create.Microsoft is not a constructor'. This suggests that you did not build it. Unfortunately, in my commit I did not build a new built/tl-create.js.

**Comment by rmhrisk** [comment]
Fixed
