### ISSUE TITLE
Unable to parse EUTL

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#38]
```
Trust Lists: EUTL
TL data: Downloading from http://ec.europa.eu/information_society/newsroom/cf/dae/document.cfm?doc_id=1789
TL data: Ok
[xmldom warning]	unclosed xml attribute 
@#[line:5,col:53]
[xmldom warning]	unclosed xml attribute 
@#[line:8,col:124]
[xmldom warning]	unclosed xml attribute 
@#[line:15,col:172]
Error: Wrong XML element Error: Wrong XML element
    at TrustServiceStatusList.LoadXml (/Users/rmh/tl-create/built/tl-create.js:326:23)
    at EUTL.parse (/Users/rmh/tl-create/built/tl-create.js:205:18)
    at parseEUTL (/Users/rmh/tl-create/src/bin/tl-create.js:116:19)
    at Object.<anonymous> (/Users/rmh/tl-create/src/bin/tl-create.js:194:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
Output format: PEM
/Users/rmh/tl-create/src/bin/tl-create.js:243
            writableStream.write(tl.toString());
                                   ^

TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (/Users/rmh/tl-create/src/bin/tl-create.js:243:36)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

```

**Comment by rmhrisk** [comment]
Fixed, the url changed
