### ISSUE TITLE
asnljs 404

### ISSUE THREAD

**Issue by tolgyesizs** [PeculiarVentures/tl-create#63]
https://registry.npmjs.org/asnl.js

Error: Cannot find module 'asn1js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/shared2/download/TL/tl-create/built/tl-create.js:585:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Registry returned 404 for GET on https://registry.npmjs.org/asnljs

How can I get a walid asnljs?

**Comment by YuryStrozhevsky** [comment]
@tolgyesizs You are using incorrect module name. Correct name is "asn1js", not "asnljs".

**Comment by tolgyesizs** [comment]
thank you, I did not see it well
everything is OK
